apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: local-path-storage
  resources:
    requests:
      storage: 10Gi

