apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocketmq-console
  name: rocketmq-console
  namespace: rocketmq
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31000
    port: 8080
    targetPort: 8080
  selector:
    app: rocketmq-console
