---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: redis-exporter
    app.kubernetes.io/name: redis-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9121
    protocol: TCP
    targetPort: 9121
    name: redis-monitor-port
  selector:
    app.kubernetes.io/name: redis-exporter
