auth_enabled: false

common:
  storage:
    s3:
      bucketnames: dev-sale-retail
      endpoint: oss-cn-beijing.aliyuncs.com
      access_key_id: LTAI5tDpfTwNrp6m1fJCJ2nD
      secret_access_key: DSviLUsIATJViYUOHc2sUN7OxIUAUV
      
server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: error

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members: 
    - loki-write-0.loki-member.loki.svc.cluster.local:7946
    - loki-write-1.loki-member.loki.svc.cluster.local:7946
    - loki-write-2.loki-member.loki.svc.cluster.local:7946
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s

schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: loki_index_
      period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 168h

  #filesystem:
  #  directory: /loki/chunks

limits_config:
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_entries_limit_per_query: 1000

chunk_store_config:
  max_look_back_period: 336h

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  parallelise_shardable_queries: true
  cache_results: true

  results_cache:
    cache:
      # We're going to use the in-process "FIFO" cache
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h
ruler:
  storage:
    type: s3
      
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-querier.loki:3100

frontend_worker:
    frontend_address: loki-frontend.loki:9095

querier:
  query_ingesters_within: 2h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
