apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  labels:
    app: redis
data:
  master.conf: |
    bind 0.0.0.0
    port 6379
    requirepass "123456"
    masterauth 123456
    loglevel warning
    logfile "/data/redis.log"
  slave.conf: |
    bind 0.0.0.0
    port 6379
    requirepass "123456"
    masterauth 123456
    slaveof redis-master.redis 6379
    loglevel warning
    logfile "/data/redis.log"
  sentinel.conf: |
    port 26379
    protected-mode no
    sentinel monitor redis-master redis-master.redis 6379 2
    sentinel down-after-milliseconds redis-master 5000
    sentinel failover-timeout redis-master 180000
    sentinel parallel-syncs redis-master 1
    sentinel auth-pass redis-master 123456
    logfile /data/redis-sentinel.log
