apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: redis
  labels:
    app: redis
spec:
  ports:
  - port: 26379
    name: redis-sentinel
  selector:
    app-sidecar: redis-sentinel
