apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: dolphinscheduler
    app.kubernetes.io/name: dolphinscheduler-worker
  name: dolphinscheduler-worker
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: dolphinscheduler
      app.kubernetes.io/name: dolphinscheduler-worker
  serviceName: dolphinscheduler-worker-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: dolphinscheduler
        app.kubernetes.io/name: dolphinscheduler-worker
    spec:
      serviceAccountName: dolphinscheduler
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: SPRING_JACKSON_TIME_ZONE
          value: Asia/Shanghai
        - name: ALERT_LISTEN_HOST
          value: dolphinscheduler-alert
        - name: DATABASE
          value: mysql
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.229.121:3306/dolphinscheduler?characterEncoding=utf8
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: REGISTRY_TYPE
          value: zookeeper
        - name: REGISTRY_ZOOKEEPER_CONNECT_STRING
          value: zk-hs.zookeeper:2181
        - name: WORKER_EXEC_THREADS
          value: "100"
        - name: WORKER_GROUPS
          value: default
        - name: WORKER_GROUPS_0
          value: default
        - name: WORKER_HEARTBEAT_INTERVAL
          value: 10s
        - name: WORKER_HEART_ERROR_THRESHOLD
          value: "5"
        - name: WORKER_HOST_WEIGHT
          value: "100"
        - name: WORKER_MAX_CPU_LOAD_AVG
          value: "-1"
        - name: WORKER_RESERVED_MEMORY
          value: "0.3"
        envFrom:
        - configMapRef:
            name: dolphinscheduler-common
        image: registry.cn-beijing.aliyuncs.com/basetools/dolphinscheduler-worker:3.1.1-mysql-hotfix
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:1235/actuator/health/liveness
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: dolphinscheduler-worker
        ports:
        - containerPort: 1234
          name: worker-port
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:1235/actuator/health/readiness
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/dolphinscheduler
          name: dolphinscheduler-worker-data
        - mountPath: /opt/dolphinscheduler/logs
          name: dolphinscheduler-worker-logs
        - mountPath: /opt/dolphinscheduler/conf/common.properties
          name: config-volume
          subPath: common_properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: dolphinscheduler-worker-data
      - emptyDir: {}
        name: dolphinscheduler-worker-logs
      - configMap:
          defaultMode: 420
          name: dolphinscheduler-configs
        name: config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
