version: '3.3'
services:
  HAProxy:
    image: haproxy:2.6.13
    restart: always
    container_name: HAProxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    network_mode: host
  keepalived:
    image: osixia/keepalived:2.0.20
    restart: always
    container_name: keepalived
    command: [--copy-service]
    depends_on:
      - HAProxy
    volumes:
      - ./keepalived.conf:/container/service/keepalived/assets/keepalived.conf
    network_mode: host
    cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
  
