apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app.kubernetes.io/component: zookeeper-exporter
        app.kubernetes.io/name: zookeeper-exporter
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: zookeeper-exporter
        image: 172.16.11.165:8088/bi/monitor/zookeeper-exporter:latest
        command: ["/usr/local/bin/zookeeper-exporter", "--listen=0.0.0.0:9104", "--zk-hosts=172.16.11.172:2181,172.16.11.183:2181,172.16.11.184:2181"]
        ports:
        - containerPort: 9104
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
