apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: mysql-exporter
    app.kubernetes.io/name: mysql-exporter
    prometheus: k8s
    role: alert-rules
  name: mysql-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: mysql-exporter
    rules:
    - alert: MysqlDown
      expr: mysql_up == 0
      for: 0m
      labels:
        type: mysql
        severity: critical
      annotations:
        description: 数据库实例{{ $labels.instance }}未运行,请检查是否宕机
        summary: "MySQL instance {{ $labels.instance }} is down"
    - alert: MysqlTooManyConnections
      expr: avg by (instance) (rate(mysql_global_status_threads_connected[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
      for: 2m
      labels:
        type: mysql
        severity: warning
      annotations:
        description: 数据库实例{{ $labels.instance }}连接数使用率大于80%,当前值为{{ $value | printf "%.2f" }}%
        summary: "More than 80% of MySQL connections are in use on {{ $labels.instance }}"
    - alert: MysqlHighThreadsRunning
      expr: avg by (instance) (rate(mysql_global_status_threads_running[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 60
      for: 2m
      labels:
        type: mysql
        severity: warning
      annotations:
        description: 数据库实例{{ $labels.instance }}超过60%的线程处于running状态,当前值为{{ $value | printf "%.2f" }}%
        summary: "More than 60% of MySQL connections are in running state on {{ $labels.instance }}"
    - alert: MysqlSlowQueries
      expr: increase(mysql_global_status_slow_queries[1m]) > 0
      for: 2m
      labels:
        type: mysql
        severity: warning
      annotations:
        description: 数据库实例{{ $labels.instance }}最近1m内有慢查询语句,数量为{{ $value }}
        summary: "MySQL server has some new slow query on {{ $labels.instance }}"
    - alert: MysqlRestarted
      expr: mysql_global_status_uptime < 60
      for: 0m
      labels:
        type: mysql
        severity: info
      annotations:
        description: 数据库实例{{ $labels.instance }}发生了重启,当前启动时间为{{ $value }}秒
        summary: "MySQL has just been restarted, less than one minute ago on {{ $labels.instance }}"
