FROM apache/dolphinscheduler-tools:3.1.1
# 拷贝mysql驱动
COPY mysql-connector-java-8.0.16.jar /opt/dolphinscheduler/tools/libs
#RUN apt-get update && \
#    apt-get install -y libsasl2-dev python3-pip && \
#    apt-get autoclean

