apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dolphinscheduler
    release: dolphinscheduler
  name: dolphinscheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: dolphinscheduler
    release: dolphinscheduler
  name: dolphinscheduler
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: dolphinscheduler
    release: dolphinscheduler
  name: dolphinscheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dolphinscheduler
subjects:
- kind: ServiceAccount
  name: dolphinscheduler
