apiVersion: v1
kind: Service
metadata:
  name: etcd-monitor
  namespace: kube-system
  labels:
    k8s-app: etcd-monitor
    app.kubernetes.io/name: etcd-monitor
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 2379
    protocol: TCP
  selector:
    component: etcd
