apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: mysql-exporter
    app.kubernetes.io/name: mysql-exporter
  name: mysql-exporter
  namespace: monitoring
spec:
 endpoints:
 selector:
   matchLabels:
     app.kubernetes.io/component: mysql-exporter
