apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-write
  labels:
    app.kubernetes.io/name: loki-write
spec:
  replicas: 3
  serviceName:  loki-member
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-write
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki-write
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - loki-write
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: loki-write
        image: grafana/loki:2.4.1
        imagePullPolicy: IfNotPresent
        args:
          - "-config.file=/etc/loki/loki.yaml"
          - "-target=write"
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: memberlist
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "1000Mi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/
          readOnly: true
        - name: loki-data
          mountPath: /loki/
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        securityContext:
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      volumes:
        - name: loki-config
          secret:
            secretName: loki-config
  volumeClaimTemplates:
  - metadata:
      name: loki-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path-storage
      resources:
        requests:
          storage: "10Gi"
        #- name: loki-data
        #  nfs:
        #    path: /data/loki
        #    server: 192.168.229.133
