---
apiVersion: v1
kind: Service
metadata:
  name: dolphinscheduler-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dolphinscheduler-api
  ports:
  - protocol: TCP
    port: 12345
    targetPort: 12345

