apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dolphinscheduler-alert
  name: dolphinscheduler-alert
spec:
  ports:
  - name: alert-port
    port: 50052
    protocol: TCP
    targetPort: alert-port
  - name: actuator-port
    port: 50053
    protocol: TCP
    targetPort: actuator-port
  selector:
    app.kubernetes.io/name: dolphinscheduler-alert
  sessionAffinity: None
  type: ClusterIP
