---
apiVersion: v1
kind: Service
metadata:
  name: dolphinscheduler-api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dolphinscheduler-api
  ports:
  - protocol: TCP
    nodePort: 30011
    port: 12345
    targetPort: 12345

